import './globals.css'
import { Inter } from 'next/font/google'
import { Navbar } from './components/Navbar/Navbar'
import { Footer } from './components/Footer'

export const metadata = {
  title: 'Heroic Games Launcher',
  description: 'Generated by create next app'
}

const inter = Inter({
  subsets: ['latin'],
  display: 'swap'
})

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}): JSX.Element {
  return (
    <html lang="en" className={inter.className}>
      <body className="dark:bg-gray-900 antialiased">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
